---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: filebeat-{{ .Values.environment }}
data:
{{- range $path, $config := .Values.filebeatConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
      output.elasticsearch:
      hosts: {{ .Values.hosts }}
      index: {{ .Values.index }}
      username: {{ .Values.username }}
      password: {{ .Values.password }}
    setup.template.name: "common-mapping"
    setup.template.pattern: "logindex-*"
    setup.ilm.enabled: false
